name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - run: node build-lib.js

      - run: pnpm run test:unit --coverage
        env:
          NODE_OPTIONS: --experimental-vm-modules

      - run: pnpm run test:types

      - run: pnpm run test:browser

      - uses: codecov/codecov-action@v3
