name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - run: node build-lib.js

      - run: pnpm run test:unit --coverage
        env:
          NODE_OPTIONS: --experimental-vm-modules

      - run: pnpm run test:types

      - run: pnpm run test:browser

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info,playwright-report/lcov.info
