name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - uses: actions/checkout@v3

      - run: npm i -g pnpm

      - run: pnpm install

      - run: node build-lib.js

      - run: pnpm run test:unit --coverage
        env:
          NODE_OPTIONS: --experimental-vm-modules

      - run: pnpm run test:types

      - uses: codecov/codecov-action@v3
